In [12]:
import numpy as np


a = np.array([[0, 0.75, 0.25],

              

              [0.9, 0, 0.1],



              [0.7, 0.3, 0]])



mod = np.array([[1/3, 1/3, 1/3],

              

              [1/3, 1/3, 1/3],



              [1/3, 1/3, 1/3]])



b = np.array([[0.5,0.25,0.25]])

alpha = 1

kaisu = 5

akaisu = np.linalg.matrix_power(alpha*a+(1-alpha)*mod, kaisu)

c1=np.dot(b, akaisu)


print(c1)


[[0.42376 0.41628 0.15996]]


In [24]:
import numpy as np


a = np.array([[0, 0.9, 0.1],

              

              [0.9, 0, 0.1],



              [0.5, 0.5, 0]])



mod = np.array([[1/3, 1/3, 1/3],

              

              [1/3, 1/3, 1/3],



              [1/3, 1/3, 1/3]])



b = np.array([[0.5,0.25,0.25]])

alpha = 1

kaisu = 25

akaisu = np.linalg.matrix_power(alpha*a+(1-alpha)*mod, kaisu)

c1=np.dot(b, akaisu)


print(c1)


[[0.44557173 0.46351918 0.09090909]]


In [19]:
import numpy as np


a = np.array([[0, 1, 0, 0, 0],

              [1/2, 0, 1/2,0, 0],

              [1/3, 0, 0, 1/3, 1/3],
              
              [1/2, 0, 0, 0, 1/2],

              [1/3,1/3,0,1/3,0]         ])



mod = np.array([[1/5, 1/5, 1/5, 1/5, 1/5],

              [1/5, 1/5, 1/5,1/5, 1/5],

              [1/5, 1/5, 1/5, 1/5, 1/5],
              
              [1/5, 1/5, 1/5, 1/5, 1/5],

              [1/5,1/5,1/5,1/5,1/5]         ])



b = np.array([[1,0,0,0,0]])

alpha = 0.85

kaisu = 10

akaisu = np.linalg.matrix_power(alpha*a+(1-alpha)*mod, kaisu)

c1=np.dot(b, akaisu)


print(c1)

[[0.29208069 0.31043471 0.16401169 0.1104645  0.12300842]]
